version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-stock
    environment:
      MYSQL_ROOT_PASSWORD: secret_stock
      MYSQL_DATABASE: stock_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
